/* =============================================================================
 * content/achievements.js — every achievement in the game.
 * -----------------------------------------------------------------------------
 * Each one earned also grants a permanent production bonus
 * (CONFIG.achievementBonusPer, plus anything from achievementBonus upgrades).
 *
 * IDS ARE SAVE KEYS. Never rename or reuse one after release.
 * ========================================================================== */
(function (DC) {
  'use strict';
  var CONFIG = DC.CONFIG;

  CONFIG.achievements = CONFIG.achievements.concat([
  { id: 'enthusiast', name: 'Durian Enthusiast', description: 'Collect 1,000 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1000 } },
  { id: 'hoarder', name: 'Durian Hoarder', description: 'Collect 1,000,000 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e6 } },
  { id: 'a_lot_of_fruit', name: 'That\'s a Lot of Fruit', description: 'Collect 1 billion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e9 } },
  { id: 'smells_like_home', name: 'Smells Like Home', description: 'Collect 1 trillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e12 } },
  { id: 'quadrillion', name: 'Quadrillion Club', description: 'Collect 1 quadrillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+15 } },
  { id: 'quintillion', name: 'Structurally Unsound', description: 'Collect 1 quintillion Durians. The warehouse is a rumour now.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+18 } },
  { id: 'sextillion', name: 'Notably Pungent', description: 'Collect 1 sextillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+21 } },
  { id: 'septillion', name: 'Detectable From Orbit', description: 'Collect 1 septillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+24 } },
  { id: 'octillion', name: 'Delfino Reeks', description: 'Collect 1 octillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+27 } },
  { id: 'nonillion', name: 'A Fruit-Based Economy', description: 'Collect 1 nonillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+30 } },
  { id: 'decillion', name: 'The Durian Age', description: 'Collect 1 decillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+33 } },
  { id: 'undecillion', name: 'Post-Fruit Society', description: 'Collect 1 undecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+36 } },
  { id: 'duodecillion', name: 'Beyond Counting', description: 'Collect 10 duodecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+40 } },
  { id: 't_1e42', name: 'Deep Field', description: 'Collect 1 tredecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+42 } },
  { id: 't_1e45', name: 'Quattuordecillion Club', description: 'Collect 1 quattuordecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+45 } },
  { id: 't_1e48', name: 'Fifteen Groups Of Three', description: 'Collect 1 quindecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+48 } },
  { id: 'absurd', name: 'This Is Absurd', description: 'Collect 100 quindecillion Durians. Genuinely, well done.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+50 } },
  { id: 't_1e51', name: 'Sexdecillion', description: 'Collect 1 sexdecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+51 } },
  { id: 't_1e55', name: 'Numbers Stop Meaning Things', description: 'Collect 10 septendecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+55 } },
  { id: 't_1e60', name: 'Vigintillionaire', description: 'Collect 1 vigintillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+60 } },
  { id: 't_1e66', name: 'Past The Suffixes', description: 'Collect 1 unvigintillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+66 } },
  { id: 't_1e72', name: 'Still Going', description: 'Collect 1 duovigintillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+72 } },
  { id: 't_1e80', name: 'More Durians Than Atoms Nearby', description: 'Collect 10 sexvigintillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+80 } },
  { id: 't_1e90', name: 'Ninety Zeroes', description: 'Collect 1 novemvigintillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+90 } },
  { id: 't_1e100', name: 'The Googol Harvest', description: 'Collect one googol Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+100 } },
  { id: 't_1e120', name: 'Why Are You Like This', description: 'Collect 10^120 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+120 } },
  { id: 't_1e150', name: 'Genuinely Concerning', description: 'Collect 10^150 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+150 } },
  { id: 't_1e200', name: 'Beyond The Suffix Table', description: 'Collect 10^200 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+200 } },
  { id: 't_1e250', name: 'Scientific Notation Only', description: 'Collect 10^250 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+250 } },
  { id: 't_1e300', name: 'The Far Shore', description: 'Collect 10^300 Durians. There is not much past here.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+300 } },
  { id: 'plaza_economy', name: 'Plaza Economy', description: 'Reach 1,000 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1000 } },
  { id: 'rate_10k', name: 'Cottage Industry', description: 'Reach 10,000 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 10000 } },
  { id: 'rate_100k', name: 'Regional Supplier', description: 'Reach 100,000 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 100000 } },
  { id: 'rate_1m', name: 'Industrial Harvest', description: 'Reach 1 million Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+06 } },
  { id: 'rate_100m', name: 'Continental Output', description: 'Reach 100 million Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+08 } },
  { id: 'rate_10b', name: 'The Firehose', description: 'Reach 10 billion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+10 } },
  { id: 'rate_1t', name: 'Faster Than Thought', description: 'Reach 1 trillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+12 } },
  { id: 'rate_1qa', name: 'Per-Second Quadrillionaire', description: 'Reach 1 quadrillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+15 } },
  { id: 'r_1e18', name: 'Quintillion A Second', description: 'Reach 1 quintillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+18 } },
  { id: 'r_1e21', name: 'Sextillion A Second', description: 'Reach 1 sextillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+21 } },
  { id: 'r_1e25', name: 'Faster Than Bookkeeping', description: 'Reach 10 septillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+25 } },
  { id: 'r_1e30', name: 'Nonillion A Second', description: 'Reach 1 nonillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+30 } },
  { id: 'r_1e40', name: 'The Firehose Widens', description: 'Reach 10^40 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+40 } },
  { id: 'r_1e50', name: 'Rate Of Absurdity', description: 'Reach 10^50 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+50 } },
  { id: 'r_1e70', name: 'Per-Second Ridiculous', description: 'Reach 10^70 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+70 } },
  { id: 'r_1e100', name: 'A Googol A Second', description: 'Reach 10^100 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+100 } },
  { id: 'first_durian', name: 'First Durian', description: 'Click the Durian for the first time.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 1 } },
  { id: 'blistered', name: 'Blistered', description: 'Click the Durian 100 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 100 } },
  { id: 'clicks_1k', name: 'Repetitive Strain', description: 'Click the Durian 1,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 1000 } },
  { id: 'clicks_5k', name: 'Dedicated', description: 'Click the Durian 5,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 5000 } },
  { id: 'clicks_25k', name: 'Concerning Commitment', description: 'Click the Durian 25,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 25000 } },
  { id: 'clicks_100k', name: 'See a Doctor', description: 'Click the Durian 100,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 100000 } },
  { id: 'c_250k', name: 'Quarter Million Taps', description: 'Click the Durian 250,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 250000 } },
  { id: 'c_500k', name: 'Half A Million', description: 'Click the Durian 500,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 500000 } },
  { id: 'c_1m', name: 'One Million Clicks', description: 'Click the Durian a million times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 1000000 } },
  { id: 'c_2m', name: 'Two Million Clicks', description: 'Click the Durian two million times. Please rest.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 2000000 } },
  { id: 'c_5m', name: 'Five Million Clicks', description: 'Click the Durian five million times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 5000000 } },
  { id: 'c_10m', name: 'Ten Million Clicks', description: 'Click the Durian ten million times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 10000000 } },
  { id: 'manual_labor', name: 'Manual Labor', description: 'Earn 100,000 Durians by clicking alone.',
    group: 'Clicking',
    condition: { type: 'clickEarned', amount: 1e5 } },
  { id: 'pianta_workforce', name: 'Pianta Workforce', description: 'Hire 10 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 10 } },
  { id: 'pianta_union', name: 'Pianta Union', description: 'Hire 50 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 50 } },
  { id: 'pianta_100', name: 'Pianta Town', description: 'Hire 100 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 100 } },
  { id: 'pianta_200', name: 'A Proper Pianta Crew', description: 'Hire 200 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 200 } },
  { id: 'pianta_250', name: 'Pianta City', description: 'Hire 250 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 250 } },
  { id: 'pianta_350', name: 'Piantas Everywhere', description: 'Hire 350 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 350 } },
  { id: 'pianta_500', name: 'Pianta Nation', description: 'Hire 500 Piantas. They were here first and they will be here last.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 500 } },
  { id: 'pianta_h600', name: 'Six Hundred Piantas', description: 'Hire 600 Piantas. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 600 } },
  { id: 'pianta_700', name: 'Seven Hundred Piantas', description: 'Hire 700 Piantas. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 700 } },
  { id: 'fruitlady_10', name: 'Market Day', description: 'Hire 10 Fruit Ladies.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 10 } },
  { id: 'fruitlady_100', name: 'The Whole Fountain', description: 'Hire 100 Fruit Ladies.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 100 } },
  { id: 'fruitlady_200', name: 'A Proper Fruit Ladie Crew', description: 'Hire 200 Fruit Ladies.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 200 } },
  { id: 'fruitlady_350', name: 'Fruit Ladies Everywhere', description: 'Hire 350 Fruit Ladies.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 350 } },
  { id: 'fruitlady_h600', name: 'Six Hundred Fruit Ladies', description: 'Hire 600 Fruit Ladies. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 600 } },
  { id: 'fruitlady_700', name: 'Seven Hundred Fruit Ladies', description: 'Hire 700 Fruit Ladies. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 700 } },
  { id: 'noki_workforce', name: 'Noki Workforce', description: 'Hire 10 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 10 } },
  { id: 'noki_100', name: 'Noki Colony', description: 'Hire 100 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 100 } },
  { id: 'noki_200', name: 'A Proper Noki Crew', description: 'Hire 200 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 200 } },
  { id: 'noki_250', name: 'Noki Metropolis', description: 'Hire 250 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 250 } },
  { id: 'noki_350', name: 'Nokis Everywhere', description: 'Hire 350 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 350 } },
  { id: 'noki_500', name: 'The Whole Bay', description: 'Hire 500 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 500 } },
  { id: 'noki_h600', name: 'Six Hundred Nokis', description: 'Hire 600 Nokis. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 600 } },
  { id: 'noki_700', name: 'Seven Hundred Nokis', description: 'Hire 700 Nokis. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 700 } },
  { id: 'yoshi_workforce', name: 'Yoshi Ranch', description: 'Hire 10 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 10 } },
  { id: 'yoshi_50', name: 'Stampede', description: 'Hire 50 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 50 } },
  { id: 'yoshi_150', name: 'Do Not Let Them Near Water', description: 'Hire 150 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 150 } },
  { id: 'yoshi_200', name: 'A Proper Yoshi Crew', description: 'Hire 200 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 200 } },
  { id: 'yoshi_350', name: 'Yoshis Everywhere', description: 'Hire 350 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 350 } },
  { id: 'yoshi_h600', name: 'Six Hundred Yoshis', description: 'Hire 600 Yoshis. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 600 } },
  { id: 'yoshi_700', name: 'Seven Hundred Yoshis', description: 'Hire 700 Yoshis. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 700 } },
  { id: 'toad_50', name: 'Brigade Strength', description: 'Hire 50 Toads.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 50 } },
  { id: 'toad_150', name: 'The Directorate', description: 'Hire 150 Toads.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 150 } },
  { id: 'toad_200', name: 'A Proper Toad Crew', description: 'Hire 200 Toads.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 200 } },
  { id: 'toad_350', name: 'Toads Everywhere', description: 'Hire 350 Toads.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 350 } },
  { id: 'toad_h600', name: 'Six Hundred Toads', description: 'Hire 600 Toads. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 600 } },
  { id: 'toad_700', name: 'Seven Hundred Toads', description: 'Hire 700 Toads. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 700 } },
  { id: 'mushroom_10', name: 'Business Is Business', description: 'Hire 10 Mushroom Dealer Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 10 } },
  { id: 'mushroom_100', name: 'Ask No Questions', description: 'Hire 100 Mushroom Dealer Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 100 } },
  { id: 'mushroompianta_200', name: 'A Proper Mushroom Dealer Crew', description: 'Hire 200 Mushroom Dealers.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 200 } },
  { id: 'mushroompianta_350', name: 'Mushroom Dealers Everywhere', description: 'Hire 350 Mushroom Dealers.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 350 } },
  { id: 'mushroompianta_h600', name: 'Six Hundred Mushroom Dealers', description: 'Hire 600 Mushroom Dealers. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 600 } },
  { id: 'mushroompianta_700', name: 'Seven Hundred Mushroom Dealers', description: 'Hire 700 Mushroom Dealers. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 700 } },
  { id: 'piantissimo_50', name: 'A Suspicious Number of Them', description: 'Hire 50 Il Piantissimos.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 50 } },
  { id: 'piantissimo_150', name: 'All Definitely Piantas', description: 'Hire 150 Il Piantissimos.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 150 } },
  { id: 'piantissimo_200', name: 'A Proper Il Piantissimo Crew', description: 'Hire 200 Il Piantissimos.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 200 } },
  { id: 'piantissimo_350', name: 'Il Piantissimos Everywhere', description: 'Hire 350 Il Piantissimos.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 350 } },
  { id: 'piantissimo_h600', name: 'Six Hundred Il Piantissimos', description: 'Hire 600 Il Piantissimos. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 600 } },
  { id: 'piantissimo_700', name: 'Seven Hundred Il Piantissimos', description: 'Hire 700 Il Piantissimos. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 700 } },
  { id: 'tanooki_10', name: 'That Tree Moved', description: 'Hire 10 Tanookis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 10 } },
  { id: 'tanooki_100', name: 'Definitely a Forest', description: 'Hire 100 Tanookis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 100 } },
  { id: 'tanooki_200', name: 'A Proper Tanooki Crew', description: 'Hire 200 Tanookis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 200 } },
  { id: 'tanooki_350', name: 'Tanookis Everywhere', description: 'Hire 350 Tanookis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 350 } },
  { id: 'tanooki_h600', name: 'Six Hundred Tanookis', description: 'Hire 600 Tanookis. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 600 } },
  { id: 'tanooki_700', name: 'Seven Hundred Tanookis', description: 'Hire 700 Tanookis. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 700 } },
  { id: 'shadow_50', name: 'Seeing Double', description: 'Hire 50 Shadow Marios.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 50 } },
  { id: 'shadow_150', name: 'Which One Is Real', description: 'Hire 150 Shadow Marios.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 150 } },
  { id: 'shadowmario_200', name: 'A Proper Shadow Mario Crew', description: 'Hire 200 Shadow Marios.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 200 } },
  { id: 'shadowmario_350', name: 'Shadow Marios Everywhere', description: 'Hire 350 Shadow Marios.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 350 } },
  { id: 'shadowmario_h600', name: 'Six Hundred Shadow Marios', description: 'Hire 600 Shadow Marios. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 600 } },
  { id: 'shadowmario_700', name: 'Seven Hundred Shadow Marios', description: 'Hire 700 Shadow Marios. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 700 } },
  { id: 'ricco_10', name: 'Perfect RNG', description: 'Hire 10 Ricco Fruit Converters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'riccoconverter', count: 10 } },
  { id: 'ricco_100', name: 'Everything Into Durians', description: 'Hire 100 Ricco Fruit Converters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'riccoconverter', count: 100 } },
  { id: 'riccoconverter_200', name: 'A Proper Ricco Converter Crew', description: 'Hire 200 Ricco Converters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'riccoconverter', count: 200 } },
  { id: 'riccoconverter_350', name: 'Ricco Converters Everywhere', description: 'Hire 350 Ricco Converters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'riccoconverter', count: 350 } },
  { id: 'riccoconverter_h600', name: 'Six Hundred Ricco Converters', description: 'Hire 600 Ricco Converters. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'riccoconverter', count: 600 } },
  { id: 'riccoconverter_700', name: 'Seven Hundred Ricco Converters', description: 'Hire 700 Ricco Converters. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'riccoconverter', count: 700 } },
  { id: 'chuckster_10', name: 'CHUCKSTER', description: 'Hire 10 Chucksters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 10 } },
  { id: 'chuckster_100', name: 'Nothing Is Carried Any More', description: 'Hire 100 Chucksters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 100 } },
  { id: 'chuckster_200', name: 'A Proper Chuckster Crew', description: 'Hire 200 Chucksters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 200 } },
  { id: 'chuckster_350', name: 'Chucksters Everywhere', description: 'Hire 350 Chucksters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 350 } },
  { id: 'chuckster_h600', name: 'Six Hundred Chucksters', description: 'Hire 600 Chucksters. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 600 } },
  { id: 'chuckster_700', name: 'Seven Hundred Chucksters', description: 'Hire 700 Chucksters. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 700 } },
  { id: 'tree_1', name: 'It Is Bursting With Fruit', description: 'Plant your first Giant Pianta Tree.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'giantpiantatree', count: 1 } },
  { id: 'tree_25', name: 'A Grove of Giants', description: 'Hire 25 Giant Pianta Trees.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'giantpiantatree', count: 25 } },
  { id: 'giantpiantatree_200', name: 'A Proper Giant Pianta Tree Crew', description: 'Hire 200 Giant Pianta Trees.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'giantpiantatree', count: 200 } },
  { id: 'giantpiantatree_350', name: 'Giant Pianta Trees Everywhere', description: 'Hire 350 Giant Pianta Trees.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'giantpiantatree', count: 350 } },
  { id: 'giantpiantatree_h600', name: 'Six Hundred Giant Pianta Trees', description: 'Hire 600 Giant Pianta Trees. This takes a while.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'giantpiantatree', count: 600 } },
  { id: 'giantpiantatree_700', name: 'Seven Hundred Giant Pianta Trees', description: 'Hire 700 Giant Pianta Trees. This takes considerably longer.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'giantpiantatree', count: 700 } },
  { id: 'staffed_up', name: 'Fully Staffed', description: 'Hire 100 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 100 } },
  { id: 'crew_250', name: 'Small Town Employer', description: 'Hire 250 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 250 } },
  { id: 'crew_500', name: 'Major Employer', description: 'Hire 500 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 500 } },
  { id: 'crew_1000', name: 'The Island Works For You', description: 'Hire 1,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 1000 } },
  { id: 'crew_2000', name: 'Nobody Is Off Duty', description: 'Hire 2,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 2000 } },
  { id: 'cs_3000', name: 'Three Thousand Strong', description: 'Hire 3,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 3000 } },
  { id: 'cs_5000', name: 'A Small Nation', description: 'Hire 5,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 5000 } },
  { id: 'cs_7500', name: 'Overemployed', description: 'Hire 7,500 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 7500 } },
  { id: 'cs_10000', name: 'Ten Thousand', description: 'Hire 10,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 10000 } },
  { id: 'cs_15000', name: 'Everyone On Delfino', description: 'Hire 15,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 15000 } },
  { id: 'shine_get', name: 'Shine Get!', description: 'Buy 10 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 10 } },
  { id: 'up_25', name: 'Well Equipped', description: 'Buy 25 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 25 } },
  { id: 'up_50', name: 'Fully Kitted', description: 'Buy 50 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 50 } },
  { id: 'up_100', name: 'Completionist', description: 'Buy 100 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 100 } },
  { id: 'up_150', name: 'Nothing Left On The Shelf', description: 'Buy 150 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 150 } },
  { id: 'u_200', name: 'Two Hundred Upgrades', description: 'Buy 200 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 200 } },
  { id: 'u_250', name: 'Well Provisioned', description: 'Buy 250 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 250 } },
  { id: 'u_300', name: 'Three Hundred Upgrades', description: 'Buy 300 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 300 } },
  { id: 'u_350', name: 'Nearly Everything', description: 'Buy 350 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 350 } },
  { id: 'u_400', name: 'Four Hundred Upgrades', description: 'Buy 400 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 400 } },
  { id: 'u_all', name: 'Bought The Shop', description: 'Buy every upgrade in the game.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 541 } },
  { id: 'event_first', name: 'Something Happened', description: 'Witness your first island event.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 1 } },
  { id: 'event_10', name: 'Regular Occurrence', description: 'Witness 10 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 10 } },
  { id: 'event_50', name: 'Island Life', description: 'Witness 50 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 50 } },
  { id: 'e_100', name: 'Hundred Happenings', description: 'Witness 100 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 100 } },
  { id: 'e_250', name: 'Local Fixture', description: 'Witness 250 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 250 } },
  { id: 'e_500', name: 'Nothing Surprises You', description: 'Witness 500 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 500 } },
  { id: 'e_1000', name: 'A Thousand Interruptions', description: 'Witness 1,000 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 1000 } },
  { id: 'e_2500', name: 'Island Historian', description: 'Witness 2,500 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 2500 } },
  { id: 'boo_5', name: 'Boo\'s Favourite', description: 'Meet King Boo 5 times. He remembers you. That is not reassuring.',
    group: 'Island events',
    condition: { type: 'eventTypeSeen', id: 'king_boo', count: 5 } },
  { id: 'sirena_5', name: 'Valued Guest', description: 'Receive 5 bills from the Sirena Beach Hotel.',
    group: 'Island events',
    condition: { type: 'eventTypeSeen', id: 'sirena_bill', count: 5 } },
  { id: 'e_boo25', name: 'On First Name Terms', description: 'Meet King Boo 25 times.',
    group: 'Island events',
    condition: { type: 'eventTypeSeen', id: 'king_boo', count: 25 } },
  { id: 'e_sirena25', name: 'Platinum Guest', description: 'Receive 25 bills from the Sirena Beach Hotel.',
    group: 'Island events',
    condition: { type: 'eventTypeSeen', id: 'sirena_bill', count: 25 } },
  { id: 'coin_first', name: 'Something Blue', description: 'Catch your first Blue Coin.',
    group: 'Blue Coins',
    condition: { type: 'coinsCollected', count: 1 } },
  { id: 'coin_10', name: 'Coin Collector', description: 'Catch 10 Blue Coins.',
    group: 'Blue Coins',
    condition: { type: 'coinsCollected', count: 10 } },
  { id: 'coin_50', name: 'Pocket Full of Blue', description: 'Catch 50 Blue Coins.',
    group: 'Blue Coins',
    condition: { type: 'coinsCollected', count: 50 } },
  { id: 'bc_100', name: 'Century Of Coins', description: 'Collect 100 Blue Coins.',
    group: 'Blue Coins',
    condition: { type: 'coinsCollected', count: 100 } },
  { id: 'bc_250', name: 'Coin Baron', description: 'Collect 250 Blue Coins.',
    group: 'Blue Coins',
    condition: { type: 'coinsCollected', count: 250 } },
  { id: 'bc_500', name: 'Five Hundred Blue Coins', description: 'Collect 500 Blue Coins.',
    group: 'Blue Coins',
    condition: { type: 'coinsCollected', count: 500 } },
  { id: 'bc_1000', name: 'A Thousand Blue Coins', description: 'Collect 1,000 Blue Coins.',
    group: 'Blue Coins',
    condition: { type: 'coinsCollected', count: 1000 } },
  { id: 'coin_hoard', name: 'Why Are You Saving These', description: 'Hold 25 Blue Coins at once.',
    group: 'Blue Coins',
    condition: { type: 'blueCoins', count: 25 } },
  { id: 'casino_first', name: 'Beginner\'s Luck', description: 'Spin the slots for the first time.',
    group: 'Casino',
    condition: { type: 'casinoSpins', count: 1 } },
  { id: 'casino_50', name: 'Regular', description: 'Spin the slots 50 times.',
    group: 'Casino',
    condition: { type: 'casinoSpins', count: 50 } },
  { id: 'casino_500', name: 'Problem', description: 'Spin the slots 500 times.',
    group: 'Casino',
    condition: { type: 'casinoSpins', count: 500 } },
  { id: 'cas_1000', name: 'High Roller', description: 'Spin the slots 1,000 times.',
    group: 'Casino',
    condition: { type: 'casinoSpins', count: 1000 } },
  { id: 'cas_5000', name: 'The House Knows You', description: 'Spin the slots 5,000 times.',
    group: 'Casino',
    condition: { type: 'casinoSpins', count: 5000 } },
  { id: 'casino_jackpot', name: 'Three Blue Coins', description: 'Hit the Blue Coin jackpot.',
    group: 'Casino',
    condition: { type: 'casinoJackpots', count: 1 } },
  { id: 'cas_j5', name: 'Five Jackpots', description: 'Hit the Blue Coin jackpot 5 times.',
    group: 'Casino',
    condition: { type: 'casinoJackpots', count: 5 } },
  { id: 'cas_j15', name: 'Fifteen Jackpots', description: 'Hit the Blue Coin jackpot 15 times.',
    group: 'Casino',
    condition: { type: 'casinoJackpots', count: 15 } },
  { id: 'cas_j40', name: 'Statistically Suspicious', description: 'Hit the Blue Coin jackpot 40 times.',
    group: 'Casino',
    condition: { type: 'casinoJackpots', count: 40 } },
  { id: 'sk_rich', name: 'Dressed For The Occasion', description: 'Own every skin and hold 100 Blue Coins.',
    group: 'Wardrobe',
    condition: { type: 'blueCoins', count: 100 } },
  { id: 'skins_3', name: 'Dressed Up', description: 'Own 3 Durian skins.',
    group: 'Wardrobe',
    condition: { type: 'skinsOwned', count: 3 } },
  { id: 'sk_5', name: 'Options', description: 'Own 5 Durian skins.',
    group: 'Wardrobe',
    condition: { type: 'skinsOwned', count: 5 } },
  { id: 'skins_10', name: 'Fashion Forward', description: 'Own 10 Durian skins.',
    group: 'Wardrobe',
    condition: { type: 'skinsOwned', count: 10 } },
  { id: 'sk_15', name: 'Extensive Wardrobe', description: 'Own 15 Durian skins.',
    group: 'Wardrobe',
    condition: { type: 'skinsOwned', count: 15 } },
  { id: 'skins_all', name: 'Complete Wardrobe', description: 'Own every Durian skin.',
    group: 'Wardrobe',
    condition: { type: 'skinsOwned', count: 19 } },
  { id: 'play_1h', name: 'Settling In', description: 'Play for one hour.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 3600 } },
  { id: 'play_24h', name: 'Resident', description: 'Play for 24 hours in total.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 86400 } },
  { id: 'p_3d', name: 'Three Days In', description: 'Play for 3 days in total.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 259200 } },
  { id: 'p_7d', name: 'A Full Week', description: 'Play for 7 days in total.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 604800 } },
  { id: 'p_14d', name: 'Fortnight', description: 'Play for 14 days in total.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 1209600 } },
  { id: 'p_30d', name: 'A Month On Delfino', description: 'Play for 30 days in total.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 2592000 } },
  { id: 'p_100d', name: 'Resident Of Isle Delfino', description: 'Play for 100 days in total.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 8640000 } },
  { id: 'p_365d', name: 'A Year On Isle Delfino', description: 'Play for 365 days in total. Somebody famous turns up.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 31536000 } },
  { id: 'off_big', name: 'Away But Working', description: 'Collect 1 quintillion Durians from offline production.',
    group: 'Dedication',
    condition: { type: 'offlineEarned', amount: 1e18 } },
  { id: 'off_huge', name: 'Absentee Tycoon', description: 'Collect 1 nonillion Durians from offline production.',
    group: 'Dedication',
    condition: { type: 'offlineEarned', amount: 1e30 } }
  ]);
})(window.DC = window.DC || {});
