/* =============================================================================
 * content/achievements.js — every achievement in the game.
 * -----------------------------------------------------------------------------
 * Each one earned also grants a permanent production bonus
 * (CONFIG.achievementBonusPer, plus anything from achievementBonus upgrades).
 *
 * IDS ARE SAVE KEYS. Never rename or reuse one after release.
 * ========================================================================== */
(function (DC) {
  'use strict';
  var CONFIG = DC.CONFIG;

  CONFIG.achievements = CONFIG.achievements.concat([
  { id: 'enthusiast', name: 'Durian Enthusiast', description: 'Collect 1,000 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1000 } },
  { id: 'hoarder', name: 'Durian Hoarder', description: 'Collect 1,000,000 Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e6 } },
  { id: 'a_lot_of_fruit', name: 'That\'s a Lot of Fruit', description: 'Collect 1 billion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e9 } },
  { id: 'smells_like_home', name: 'Smells Like Home', description: 'Collect 1 trillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e12 } },
  { id: 'quadrillion', name: 'Quadrillion Club', description: 'Collect 1 quadrillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+15 } },
  { id: 'quintillion', name: 'Structurally Unsound', description: 'Collect 1 quintillion Durians. The warehouse is a rumour now.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+18 } },
  { id: 'sextillion', name: 'Notably Pungent', description: 'Collect 1 sextillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+21 } },
  { id: 'septillion', name: 'Detectable From Orbit', description: 'Collect 1 septillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+24 } },
  { id: 'octillion', name: 'Delfino Reeks', description: 'Collect 1 octillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+27 } },
  { id: 'nonillion', name: 'A Fruit-Based Economy', description: 'Collect 1 nonillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+30 } },
  { id: 'decillion', name: 'The Durian Age', description: 'Collect 1 decillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+33 } },
  { id: 'undecillion', name: 'Post-Fruit Society', description: 'Collect 1 undecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+36 } },
  { id: 'duodecillion', name: 'Beyond Counting', description: 'Collect 10 duodecillion Durians.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+40 } },
  { id: 'absurd', name: 'This Is Absurd', description: 'Collect 100 quindecillion Durians. Genuinely, well done.',
    group: 'Durians earned',
    condition: { type: 'totalEarned', amount: 1e+50 } },
  { id: 'plaza_economy', name: 'Plaza Economy', description: 'Reach 1,000 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1000 } },
  { id: 'rate_10k', name: 'Cottage Industry', description: 'Reach 10,000 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 10000 } },
  { id: 'rate_100k', name: 'Regional Supplier', description: 'Reach 100,000 Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 100000 } },
  { id: 'rate_1m', name: 'Industrial Harvest', description: 'Reach 1 million Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+06 } },
  { id: 'rate_100m', name: 'Continental Output', description: 'Reach 100 million Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+08 } },
  { id: 'rate_10b', name: 'The Firehose', description: 'Reach 10 billion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+10 } },
  { id: 'rate_1t', name: 'Faster Than Thought', description: 'Reach 1 trillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+12 } },
  { id: 'rate_1qa', name: 'Per-Second Quadrillionaire', description: 'Reach 1 quadrillion Durians per second.',
    group: 'Production rate',
    condition: { type: 'dps', amount: 1e+15 } },
  { id: 'first_durian', name: 'First Durian', description: 'Click the Durian for the first time.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 1 } },
  { id: 'blistered', name: 'Blistered', description: 'Click the Durian 100 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 100 } },
  { id: 'manual_labor', name: 'Manual Labor', description: 'Earn 100,000 Durians by clicking alone.',
    group: 'Clicking',
    condition: { type: 'clickEarned', amount: 1e5 } },
  { id: 'clicks_1k', name: 'Repetitive Strain', description: 'Click the Durian 1,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 1000 } },
  { id: 'clicks_5k', name: 'Dedicated', description: 'Click the Durian 5,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 5000 } },
  { id: 'clicks_25k', name: 'Concerning Commitment', description: 'Click the Durian 25,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 25000 } },
  { id: 'clicks_100k', name: 'See a Doctor', description: 'Click the Durian 100,000 times.',
    group: 'Clicking',
    condition: { type: 'clicks', count: 100000 } },
  { id: 'pianta_workforce', name: 'Pianta Workforce', description: 'Hire 10 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 10 } },
  { id: 'pianta_union', name: 'Pianta Union', description: 'Hire 50 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 50 } },
  { id: 'noki_workforce', name: 'Noki Workforce', description: 'Hire 10 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 10 } },
  { id: 'yoshi_workforce', name: 'Yoshi Ranch', description: 'Hire 10 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 10 } },
  { id: 'pianta_100', name: 'Pianta Town', description: 'Hire 100 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 100 } },
  { id: 'pianta_250', name: 'Pianta City', description: 'Hire 250 Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 250 } },
  { id: 'pianta_500', name: 'Pianta Nation', description: 'Hire 500 Piantas. They were here first and they will be here last.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'pianta', count: 500 } },
  { id: 'noki_100', name: 'Noki Colony', description: 'Hire 100 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 100 } },
  { id: 'noki_250', name: 'Noki Metropolis', description: 'Hire 250 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 250 } },
  { id: 'noki_500', name: 'The Whole Bay', description: 'Hire 500 Nokis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'noki', count: 500 } },
  { id: 'yoshi_50', name: 'Stampede', description: 'Hire 50 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 50 } },
  { id: 'yoshi_150', name: 'Do Not Let Them Near Water', description: 'Hire 150 Yoshis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'yoshi', count: 150 } },
  { id: 'toad_50', name: 'Brigade Strength', description: 'Hire 50 Toads.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 50 } },
  { id: 'toad_150', name: 'The Directorate', description: 'Hire 150 Toads.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'toad', count: 150 } },
  { id: 'piantissimo_50', name: 'A Suspicious Number of Them', description: 'Hire 50 Il Piantissimos.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 50 } },
  { id: 'piantissimo_150', name: 'All Definitely Piantas', description: 'Hire 150 Il Piantissimos.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'piantissimo', count: 150 } },
  { id: 'shadow_50', name: 'Seeing Double', description: 'Hire 50 Shadow Marios.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 50 } },
  { id: 'shadow_150', name: 'Which One Is Real', description: 'Hire 150 Shadow Marios.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'shadowmario', count: 150 } },
  { id: 'fruitlady_10', name: 'Market Day', description: 'Hire 10 Fruit Ladies.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 10 } },
  { id: 'fruitlady_100', name: 'The Whole Fountain', description: 'Hire 100 Fruit Ladies.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'fruitlady', count: 100 } },
  { id: 'mushroom_10', name: 'Business Is Business', description: 'Hire 10 Mushroom Dealer Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 10 } },
  { id: 'mushroom_100', name: 'Ask No Questions', description: 'Hire 100 Mushroom Dealer Piantas.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'mushroompianta', count: 100 } },
  { id: 'tanooki_10', name: 'That Tree Moved', description: 'Hire 10 Tanookis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 10 } },
  { id: 'tanooki_100', name: 'Definitely a Forest', description: 'Hire 100 Tanookis.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'tanooki', count: 100 } },
  { id: 'chuckster_10', name: 'CHUCKSTER', description: 'Hire 10 Chucksters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 10 } },
  { id: 'chuckster_100', name: 'Nothing Is Carried Any More', description: 'Hire 100 Chucksters.',
    group: 'Crew',
    condition: { type: 'workerCount', id: 'chuckster', count: 100 } },
  { id: 'staffed_up', name: 'Fully Staffed', description: 'Hire 100 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 100 } },
  { id: 'crew_250', name: 'Small Town Employer', description: 'Hire 250 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 250 } },
  { id: 'crew_500', name: 'Major Employer', description: 'Hire 500 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 500 } },
  { id: 'crew_1000', name: 'The Island Works For You', description: 'Hire 1,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 1000 } },
  { id: 'crew_2000', name: 'Nobody Is Off Duty', description: 'Hire 2,000 workers in total.',
    group: 'Crew size',
    condition: { type: 'totalWorkers', count: 2000 } },
  { id: 'shine_get', name: 'Shine Get!', description: 'Buy 10 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 10 } },
  { id: 'up_25', name: 'Well Equipped', description: 'Buy 25 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 25 } },
  { id: 'up_50', name: 'Fully Kitted', description: 'Buy 50 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 50 } },
  { id: 'up_100', name: 'Completionist', description: 'Buy 100 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 100 } },
  { id: 'up_150', name: 'Nothing Left On The Shelf', description: 'Buy 150 upgrades.',
    group: 'Upgrades',
    condition: { type: 'upgradesBought', count: 150 } },
  { id: 'event_first', name: 'Something Happened', description: 'Witness your first island event.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 1 } },
  { id: 'event_10', name: 'Regular Occurrence', description: 'Witness 10 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 10 } },
  { id: 'event_50', name: 'Island Life', description: 'Witness 50 island events.',
    group: 'Island events',
    condition: { type: 'eventsSeen', count: 50 } },
  { id: 'boo_5', name: 'Boo\'s Favourite', description: 'Meet King Boo 5 times. He remembers you. That is not reassuring.',
    group: 'Island events',
    condition: { type: 'eventTypeSeen', id: 'king_boo', count: 5 } },
  { id: 'sirena_5', name: 'Valued Guest', description: 'Receive 5 bills from the Sirena Beach Hotel.',
    group: 'Island events',
    condition: { type: 'eventTypeSeen', id: 'sirena_bill', count: 5 } },
  { id: 'play_1h', name: 'Settling In', description: 'Play for one hour.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 3600 } },
  { id: 'play_24h', name: 'Resident', description: 'Play for 24 hours in total.',
    group: 'Dedication',
    condition: { type: 'playTime', seconds: 86400 } }
  ]);
})(window.DC = window.DC || {});
