/* =============================================================================
 * content/upgrades.js — every upgrade in the game.
 * -----------------------------------------------------------------------------
 * Split out of config.js in Update 2, because there are rather a lot of them
 * now. Adding one is still a single entry; see README.md for the effect types.
 *
 * IDS ARE SAVE KEYS. Never rename or reuse one after release.
 * ========================================================================== */
(function (DC) {
  'use strict';
  var CONFIG = DC.CONFIG;

  CONFIG.upgrades = CONFIG.upgrades.concat([
  { id: 'gloves', name: 'Better Durian Gloves',
    description: '+1 Durian per click.',
    cost: 100, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickAdd', value: 1 }],
    unlock: { type: 'clicks', count: 15 } },
  { id: 'gloves2', name: 'Reinforced Gloves',
    description: '+5 Durians per click. The spikes stop being a problem.',
    cost: 1500, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickAdd', value: 5 }],
    unlock: { type: 'upgrade', id: 'gloves' } },
  { id: 'fludd_squirt', name: 'FLUDD Squirt Nozzle',
    description: 'Blast durians off the branch. Doubles Durians per click.',
    cost: 6000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickMult', value: 2 }],
    unlock: { type: 'clicks', count: 150 } },
  { id: 'fludd_hover', name: 'Hover Nozzle',
    description: 'Each click also earns 0.2% of your Durians per second.',
    cost: 90000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromDps', value: 0.002 }],
    unlock: { type: 'upgrade', id: 'fludd_squirt' } },
  { id: 'fludd_turbo', name: 'Turbo Nozzle',
    description: 'Each click earns a further 0.2% of your Durians per second.',
    cost: 3000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromDps', value: 0.002 }],
    unlock: { type: 'upgrade', id: 'fludd_hover' } },
  { id: 'pianta_training', name: 'Pianta Training',
    description: 'Piantas produce 2x as many Durians.',
    cost: 750, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 5 } },
  { id: 'pianta_festival', name: 'Festival Overtime',
    description: 'Piantas produce 2x as many Durians.',
    cost: 13500, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 25 } },
  { id: 'noki_logistics', name: 'Noki Logistics',
    description: 'Nokis produce 2x as many Durians.',
    cost: 3750, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 5 } },
  { id: 'noki_shells', name: 'Bigger Shells',
    description: 'Nokis produce 2x as many Durians.',
    cost: 60000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 25 } },
  { id: 'yoshi_juice', name: 'Endless Juice',
    description: 'Yoshis produce 2x as many Durians.',
    cost: 37500, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 5 } },
  { id: 'toad_brigade', name: 'Toad Brigade',
    description: 'Toads produce 2x as many Durians.',
    cost: 450000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 5 } },
  { id: 'piantissimo_shoes', name: 'Suspicious Running Shoes',
    description: 'Il Piantissimo produces 2x as many Durians.',
    cost: 4500000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 5 } },
  { id: 'shadow_brush', name: 'Magic Paintbrush',
    description: 'Shadow Marios produce 2x as many Durians.',
    cost: 45000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 5 } },
  { id: 'farming', name: 'Durian Farming Techniques',
    description: 'All workers produce +10% Durians.',
    cost: 15000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.1 }],
    unlock: { type: 'totalWorkers', count: 20 } },
  { id: 'irrigation', name: 'Delfino Irrigation',
    description: 'All workers produce +15% Durians.',
    cost: 600000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.15 }],
    unlock: { type: 'totalWorkers', count: 75 } },
  { id: 'shine_blessing', name: 'Blessing of the Shine Sprites',
    description: 'All workers produce +25% Durians.',
    cost: 18000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.25 }],
    unlock: { type: 'totalWorkers', count: 150 } },
  { id: 'pianta_t3', name: 'Sunscreen Rations',
    description: 'Piantas produce twice as many Durians. Fewer breaks in the shade. Marginally fewer.',
    cost: 300000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 50 } },
  { id: 'pianta_t4', name: 'Bigger Baskets',
    description: 'Piantas produce twice as many Durians. Structural engineering, applied to fruit.',
    cost: 3000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 100 } },
  { id: 'pianta_t5', name: 'Coconut Wagons',
    description: 'Piantas produce twice as many Durians. The wheel arrives on Isle Delfino. Late, but it arrives.',
    cost: 30000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 150 } },
  { id: 'pianta_t6', name: 'Union Negotiations',
    description: 'Piantas produce twice as many Durians. Everyone got a raise. Output went up anyway.',
    cost: 300000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 200 } },
  { id: 'pianta_t7', name: 'Leaf-Blower Harvesters',
    description: 'Piantas produce twice as many Durians. Point it at the tree. Stand well back.',
    cost: 3000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 250 } },
  { id: 'pianta_t8', name: 'Pianta Public Radio',
    description: 'Piantas produce twice as many Durians. Nine hours a day of durian-related programming.',
    cost: 30000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 300 } },
  { id: 'pianta_t9', name: 'Ancestral Durian Lore',
    description: 'Piantas produce twice as many Durians. Passed down through generations. Mostly about smell.',
    cost: 300000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 350 } },
  { id: 'pianta_t10', name: 'The Chief\'s Personal Interest',
    description: 'Piantas produce twice as many Durians. He has opinions now. Everyone is working harder.',
    cost: 3000000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 400 } },
  { id: 'pianta_t11', name: 'Pianta Standard Time',
    description: 'Piantas produce twice as many Durians. The island\'s clocks now measure output, not hours.',
    cost: 30000000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 450 } },
  { id: 'pianta_t12', name: 'Manifest Durian',
    description: 'Piantas produce twice as many Durians. It is simply understood that the fruit belongs to the Piantas.',
    cost: 300000000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerMult', target: 'pianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 500 } },
  { id: 'noki_t3', name: 'Tide Charts',
    description: 'Nokis produce twice as many Durians. Working with the water instead of against it.',
    cost: 2250000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 50 } },
  { id: 'noki_t4', name: 'Polished Shells',
    description: 'Nokis produce twice as many Durians. Drag coefficient down. Morale up.',
    cost: 22500000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 100 } },
  { id: 'noki_t5', name: 'Reef Highways',
    description: 'Nokis produce twice as many Durians. Two lanes each way, coral median.',
    cost: 225000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 150 } },
  { id: 'noki_t6', name: 'Bottled Currents',
    description: 'Nokis produce twice as many Durians. They caught a current in a jar. Nobody questions it.',
    cost: 2250000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 200 } },
  { id: 'noki_t7', name: 'Shell Aerodynamics',
    description: 'Nokis produce twice as many Durians. Wind tunnel tested, somehow, underwater.',
    cost: 22500000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 250 } },
  { id: 'noki_t8', name: 'Deep Trench Routes',
    description: 'Nokis produce twice as many Durians. Shorter, darker, considerably more efficient.',
    cost: 225000000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 300 } },
  { id: 'noki_t9', name: 'Noki Elders\' Wisdom',
    description: 'Nokis produce twice as many Durians. Four hours of advice. Twelve seconds of it useful.',
    cost: 2250000000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 350 } },
  { id: 'noki_t10', name: 'The Great Shell Migration',
    description: 'Nokis produce twice as many Durians. The whole colony moves at once. So does the fruit.',
    cost: 22500000000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 400 } },
  { id: 'noki_t11', name: 'Pressure-Proof Lungs',
    description: 'Nokis produce twice as many Durians. Depth is no longer a variable.',
    cost: 225000000000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 450 } },
  { id: 'noki_t12', name: 'Abyssal Logistics',
    description: 'Nokis produce twice as many Durians. Freight routes that have never seen sunlight.',
    cost: 2250000000000000.0, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerMult', target: 'noki', value: 2 }],
    unlock: { type: 'workerCount', id: 'noki', count: 500 } },
  { id: 'yoshi_t3', name: 'Fruit Preference Survey',
    description: 'Yoshis produce twice as many Durians. Results inconclusive. They eat everything.',
    cost: 24750000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 50 } },
  { id: 'yoshi_t4', name: 'Tongue Extension Program',
    description: 'Yoshis produce twice as many Durians. Reach improved by an alarming margin.',
    cost: 247500000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 100 } },
  { id: 'yoshi_t5', name: 'Egg Delivery Service',
    description: 'Yoshis produce twice as many Durians. The eggs contain more durians. Do not ask.',
    cost: 2475000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 150 } },
  { id: 'yoshi_t6', name: 'Dismount Insurance',
    description: 'Yoshis produce twice as many Durians. Covers the Yoshi, not you.',
    cost: 24750000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 200 } },
  { id: 'yoshi_t7', name: 'Water-Resistant Coating',
    description: 'Yoshis produce twice as many Durians. A long-standing problem, finally addressed.',
    cost: 247500000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 250 } },
  { id: 'yoshi_t8', name: 'Yoshi Stampede',
    description: 'Yoshis produce twice as many Durians. Beautiful from a distance. Only from a distance.',
    cost: 2475000000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 300 } },
  { id: 'yoshi_t9', name: 'Selective Breeding',
    description: 'Yoshis produce twice as many Durians. Bred for appetite. It worked too well.',
    cost: 24750000000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 350 } },
  { id: 'yoshi_t10', name: 'The Yoshi Council',
    description: 'Yoshis produce twice as many Durians. They convene. Fruit appears. No minutes are kept.',
    cost: 247500000000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 400 } },
  { id: 'yoshi_t11', name: 'Infinite Appetite',
    description: 'Yoshis produce twice as many Durians. The stomach is now a supply line.',
    cost: 2475000000000000.0, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 450 } },
  { id: 'yoshi_t12', name: 'Yoshi Singularity',
    description: 'Yoshis produce twice as many Durians. Fruit in, more fruit out. Physicists are upset.',
    cost: 2.475e+16, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerMult', target: 'yoshi', value: 2 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 500 } },
  { id: 'toad_t3', name: 'Hotel Overtime',
    description: 'Toads produce twice as many Durians. Their vacation ended some time ago.',
    cost: 270000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 50 } },
  { id: 'toad_t4', name: 'Cap Storage Compartments',
    description: 'Toads produce twice as many Durians. Turns out there was room in there.',
    cost: 2700000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 100 } },
  { id: 'toad_t5', name: 'Chain of Command',
    description: 'Toads produce twice as many Durians. Someone finally put a Toad in charge of the Toads.',
    cost: 27000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 150 } },
  { id: 'toad_t6', name: 'Mushroom Rations',
    description: 'Toads produce twice as many Durians. Morale-neutral. Output-positive.',
    cost: 270000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 200 } },
  { id: 'toad_t7', name: 'Emergency Toad Reserves',
    description: 'Toads produce twice as many Durians. Kept in a cupboard. Deployed on request.',
    cost: 2700000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 250 } },
  { id: 'toad_t8', name: 'Toad Union Charter',
    description: 'Toads produce twice as many Durians. Collective bargaining, collective harvesting.',
    cost: 27000000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 300 } },
  { id: 'toad_t9', name: 'Spore Propagation',
    description: 'Toads produce twice as many Durians. More Toads appear. Nobody hired them.',
    cost: 270000000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 350 } },
  { id: 'toad_t10', name: 'The Toad Directorate',
    description: 'Toads produce twice as many Durians. It has a logo now. And a five-year plan.',
    cost: 2700000000000000.0, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 400 } },
  { id: 'toad_t11', name: 'Fungal Network',
    description: 'Toads produce twice as many Durians. They stopped talking out loud years ago.',
    cost: 2.7e+16, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 450 } },
  { id: 'toad_t12', name: 'Toad Hivemind',
    description: 'Toads produce twice as many Durians. One mind, ten thousand hats, all the durians.',
    cost: 2.7e+17, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerMult', target: 'toad', value: 2 }],
    unlock: { type: 'workerCount', id: 'toad', count: 500 } },
  { id: 'piantissimo_t3', name: 'Aerodynamic Mask',
    description: 'Il Piantissimo produce twice as many Durians. The mask was always aerodynamic. Now it is officially so.',
    cost: 2925000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 50 } },
  { id: 'piantissimo_t4', name: 'Pre-Race Stretching',
    description: 'Il Piantissimo produce twice as many Durians. Twenty minutes. Every time. Without exception.',
    cost: 29250000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 100 } },
  { id: 'piantissimo_t5', name: 'Head Start Policy',
    description: 'Il Piantissimo produce twice as many Durians. He wrote the policy. He also enforces it.',
    cost: 292500000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 150 } },
  { id: 'piantissimo_t6', name: 'Definitely Legal Supplements',
    description: 'Il Piantissimo produce twice as many Durians. The label says so, in very small print.',
    cost: 2925000000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 200 } },
  { id: 'piantissimo_t7', name: 'Photo Finish Appeals',
    description: 'Il Piantissimo produce twice as many Durians. He has never lost an appeal. Or filed one he lost.',
    cost: 29250000000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 250 } },
  { id: 'piantissimo_t8', name: 'Rival Intimidation',
    description: 'Il Piantissimo produce twice as many Durians. The other racers have taken up gardening instead.',
    cost: 292500000000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 300 } },
  { id: 'piantissimo_t9', name: 'Sponsorship Deal',
    description: 'Il Piantissimo produce twice as many Durians. His shirt is now covered in durian advertising.',
    cost: 2925000000000000.0, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 350 } },
  { id: 'piantissimo_t10', name: 'The Piantissimo Invitational',
    description: 'Il Piantissimo produce twice as many Durians. He invites himself. He wins.',
    cost: 2.925e+16, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 400 } },
  { id: 'piantissimo_t11', name: 'Nobody Asks Questions',
    description: 'Il Piantissimo produce twice as many Durians. About the mask. Or the voice. Or any of it.',
    cost: 2.925e+17, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 450 } },
  { id: 'piantissimo_t12', name: 'Undefeated Champion',
    description: 'Il Piantissimo produce twice as many Durians. The record book has one name in it, repeated.',
    cost: 2.925e+18, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerMult', target: 'piantissimo', value: 2 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 500 } },
  { id: 'fruitlady_t3', name: 'Ripeness Instinct',
    description: 'Fruit Ladies produce twice as many Durians. She can tell by the smell alone. Everyone can, but she is right.',
    cost: 3000.0000000000005, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 25 } },
  { id: 'fruitlady_t4', name: 'Prime Stall Position',
    description: 'Fruit Ladies produce twice as many Durians. Right by the fountain. Worth fighting for.',
    cost: 30000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 75 } },
  { id: 'fruitlady_t5', name: 'Loyal Regulars',
    description: 'Fruit Ladies produce twice as many Durians. They queue before she opens.',
    cost: 300000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 125 } },
  { id: 'fruitlady_t6', name: 'Bulk Discount',
    description: 'Fruit Ladies produce twice as many Durians. Buy nine durians, carry nine durians home, regret nothing.',
    cost: 3000000.0000000005, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 175 } },
  { id: 'fruitlady_t7', name: 'The Family Recipe',
    description: 'Fruit Ladies produce twice as many Durians. It is just a durian. She insists there is a recipe.',
    cost: 30000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 225 } },
  { id: 'fruitlady_t8', name: 'Market Monopoly',
    description: 'Fruit Ladies produce twice as many Durians. Every stall in the Plaza is hers now. They were always hers.',
    cost: 300000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 275 } },
  { id: 'fruitlady_t9', name: 'Import Licences',
    description: 'Fruit Ladies produce twice as many Durians. Fruit arriving from islands nobody can point to.',
    cost: 3000000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 325 } },
  { id: 'fruitlady_t10', name: 'The Fruit Guild',
    description: 'Fruit Ladies produce twice as many Durians. Membership is hereditary and the dues are enormous.',
    cost: 30000000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 375 } },
  { id: 'fruitlady_t11', name: 'Wholesale Empire',
    description: 'Fruit Ladies produce twice as many Durians. She sets the price of durians. All of them.',
    cost: 300000000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 425 } },
  { id: 'fruitlady_t12', name: 'Matriarch of the Market',
    description: 'Fruit Ladies produce twice as many Durians. The Plaza economy runs on her approval.',
    cost: 3000000000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerMult', target: 'fruitlady', value: 2 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 475 } },
  { id: 'mushroompianta_t3', name: 'Better Signage',
    description: 'Mushroom Dealers produce twice as many Durians. Hand-painted. Aggressively cheerful.',
    cost: 3400000.0000000005, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 25 } },
  { id: 'mushroompianta_t4', name: 'Repeat Customers',
    description: 'Mushroom Dealers produce twice as many Durians. They keep coming back. Everyone finds that normal.',
    cost: 34000000, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 75 } },
  { id: 'mushroompianta_t5', name: 'Bulk Sourcing',
    description: 'Mushroom Dealers produce twice as many Durians. The mushrooms come from somewhere. He is vague about it.',
    cost: 340000000, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 125 } },
  { id: 'mushroompianta_t6', name: 'Preferred Rates',
    description: 'Mushroom Dealers produce twice as many Durians. Durians only. Cash is refused without explanation.',
    cost: 3400000000.0000005, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 175 } },
  { id: 'mushroompianta_t7', name: 'A Second Stall',
    description: 'Mushroom Dealers produce twice as many Durians. Same Pianta. Different beach. Identical patter.',
    cost: 33999999999.999996, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 225 } },
  { id: 'mushroompianta_t8', name: 'Regional Distribution',
    description: 'Mushroom Dealers produce twice as many Durians. The stalls have a supply chain now.',
    cost: 340000000000, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 275 } },
  { id: 'mushroompianta_t9', name: 'Vertical Integration',
    description: 'Mushroom Dealers produce twice as many Durians. He grows them, sells them and buys them back.',
    cost: 3400000000000, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 325 } },
  { id: 'mushroompianta_t10', name: 'The Mushroom Cartel',
    description: 'Mushroom Dealers produce twice as many Durians. Prices are agreed at a meeting nobody admits attending.',
    cost: 33999999999999.996, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 375 } },
  { id: 'mushroompianta_t11', name: 'Nobody Audits Him',
    description: 'Mushroom Dealers produce twice as many Durians. The paperwork is immaculate and entirely fictional.',
    cost: 340000000000000, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 425 } },
  { id: 'mushroompianta_t12', name: 'Fungal Fortune',
    description: 'Mushroom Dealers produce twice as many Durians. He is the richest Pianta on the island. He still runs the stall.',
    cost: 3400000000000000.0, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerMult', target: 'mushroompianta', value: 2 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 475 } },
  { id: 'tanooki_t3', name: 'Convincing Bark',
    description: 'Tanookis produce twice as many Durians. You would walk past it. People do.',
    cost: 36000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 25 } },
  { id: 'tanooki_t4', name: 'Deeper Roots',
    description: 'Tanookis produce twice as many Durians. It stands there for days. It is being paid by the day.',
    cost: 360000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 75 } },
  { id: 'tanooki_t5', name: 'Statue Mode',
    description: 'Tanookis produce twice as many Durians. A different disguise entirely. Somehow also fruit-bearing.',
    cost: 3600000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 125 } },
  { id: 'tanooki_t6', name: 'Seasonal Foliage',
    description: 'Tanookis produce twice as many Durians. It changes colour on schedule. Nobody asked it to.',
    cost: 36000000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 175 } },
  { id: 'tanooki_t7', name: 'Orchard Camouflage',
    description: 'Tanookis produce twice as many Durians. An entire grove, and not one of them is a tree.',
    cost: 360000000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 225 } },
  { id: 'tanooki_t8', name: 'Leaf Multiplication',
    description: 'Tanookis produce twice as many Durians. More leaves, more fruit, same amount of Tanooki.',
    cost: 3600000000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 275 } },
  { id: 'tanooki_t9', name: 'Transformation Mastery',
    description: 'Tanookis produce twice as many Durians. It can be two trees now. Do not think about it.',
    cost: 36000000000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 325 } },
  { id: 'tanooki_t10', name: 'The Forest That Moves',
    description: 'Tanookis produce twice as many Durians. Counted yesterday. Counted today. Different numbers.',
    cost: 360000000000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 375 } },
  { id: 'tanooki_t11', name: 'Botanically Impossible',
    description: 'Tanookis produce twice as many Durians. Three separate surveys have given up.',
    cost: 3600000000000000.0, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 425 } },
  { id: 'tanooki_t12', name: 'Nobody Questions the Trees',
    description: 'Tanookis produce twice as many Durians. It is simply accepted. The harvest is excellent.',
    cost: 3.6e+16, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerMult', target: 'tanooki', value: 2 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 475 } },
  { id: 'chuckster_t3', name: 'Better Footing',
    description: 'Chucksters produce twice as many Durians. The throw is only as good as the stance.',
    cost: 1200000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 25 } },
  { id: 'chuckster_t4', name: 'Follow Through',
    description: 'Chucksters produce twice as many Durians. Distance improved by roughly a beach.',
    cost: 12000000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 75 } },
  { id: 'chuckster_t5', name: 'Spotter Training',
    description: 'Chucksters produce twice as many Durians. Someone shouts where it lands. Usually in time.',
    cost: 120000000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 125 } },
  { id: 'chuckster_t6', name: 'Reinforced Crates',
    description: 'Chucksters produce twice as many Durians. The fruit now survives the landing. Mostly.',
    cost: 1200000000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 175 } },
  { id: 'chuckster_t7', name: 'Long-Range Chucking',
    description: 'Chucksters produce twice as many Durians. Bay to bay, in one motion.',
    cost: 12000000000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 225 } },
  { id: 'chuckster_t8', name: 'Chuckster Academy',
    description: 'Chucksters produce twice as many Durians. Enrolment is not voluntary and nobody leaves.',
    cost: 120000000000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 275 } },
  { id: 'chuckster_t9', name: 'Ballistic Calculations',
    description: 'Chucksters produce twice as many Durians. They worked out the maths. It made them worse for a week.',
    cost: 1200000000000000.0, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 325 } },
  { id: 'chuckster_t10', name: 'Chain Chucking',
    description: 'Chucksters produce twice as many Durians. Chuckster to Chuckster to Chuckster to the warehouse.',
    cost: 1.2e+16, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 375 } },
  { id: 'chuckster_t11', name: 'Orbital Throw',
    description: 'Chucksters produce twice as many Durians. It comes down eventually. Somewhere.',
    cost: 1.2e+17, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 425 } },
  { id: 'chuckster_t12', name: 'CHUCKSTER',
    description: 'Chucksters produce twice as many Durians. There is nothing more to add. That is the whole thing.',
    cost: 1.2e+18, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerMult', target: 'chuckster', value: 2 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 475 } },
  { id: 'riccoconverter_t3', name: 'Calibrated Intake',
    description: 'Ricco Converters produce twice as many Durians. Feed it anything. It prefers not to be told what.',
    cost: 350000000, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 25 } },
  { id: 'riccoconverter_t4', name: 'Wider Hopper',
    description: 'Ricco Converters produce twice as many Durians. Whole crates now. Crates included.',
    cost: 3499999999.9999995, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 75 } },
  { id: 'riccoconverter_t5', name: 'Pineapple Conversion',
    description: 'Ricco Converters produce twice as many Durians. The first successful trial. Nobody mentions trial one.',
    cost: 35000000000, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 125 } },
  { id: 'riccoconverter_t6', name: 'Coconut Throughput',
    description: 'Ricco Converters produce twice as many Durians. Harder shell, same result, louder noise.',
    cost: 350000000000, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 175 } },
  { id: 'riccoconverter_t7', name: 'Continuous Feed',
    description: 'Ricco Converters produce twice as many Durians. It stopped needing an operator some time ago.',
    cost: 3499999999999.9995, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 225 } },
  { id: 'riccoconverter_t8', name: 'Lossless Conversion',
    description: 'Ricco Converters produce twice as many Durians. Nothing goes in that does not come out as durian.',
    cost: 35000000000000.004, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 275 } },
  { id: 'riccoconverter_t9', name: 'Overclocked Rollers',
    description: 'Ricco Converters produce twice as many Durians. The harbour can hear it from the far dock.',
    cost: 350000000000000, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 325 } },
  { id: 'riccoconverter_t10', name: 'Conversion Cascade',
    description: 'Ricco Converters produce twice as many Durians. The output goes back in. It works. It should not.',
    cost: 3499999999999999.5, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 375 } },
  { id: 'riccoconverter_t11', name: 'Perfect Yield',
    description: 'Ricco Converters produce twice as many Durians. Every single time. Every single fruit.',
    cost: 3.5000000000000004e+16, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 425 } },
  { id: 'riccoconverter_t12', name: 'It Converts Anything Now',
    description: 'Ricco Converters produce twice as many Durians. Please keep your hands clear of the intake.',
    cost: 3.5e+17, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerMult', target: 'riccoconverter', value: 2 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 475 } },
  { id: 'giantpiantatree_t3', name: 'Spring Bloom',
    description: 'Giant Pianta Trees produce twice as many Durians. The whole canopy turns at once, and the village stops to watch.',
    cost: 16000000000.000002, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 25 } },
  { id: 'giantpiantatree_t4', name: 'Deeper Roots',
    description: 'Giant Pianta Trees produce twice as many Durians. It has found water nobody knew was there.',
    cost: 160000000000, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 75 } },
  { id: 'giantpiantatree_t5', name: 'Canopy Walkways',
    description: 'Giant Pianta Trees produce twice as many Durians. Harvesting from above, finally.',
    cost: 1600000000000, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 125 } },
  { id: 'giantpiantatree_t6', name: 'Village Irrigation',
    description: 'Giant Pianta Trees produce twice as many Durians. Every household gives it a share of their water.',
    cost: 16000000000000.002, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 175 } },
  { id: 'giantpiantatree_t7', name: 'Sacred Grove Status',
    description: 'Giant Pianta Trees produce twice as many Durians. Officially protected. Unofficially, heavily farmed.',
    cost: 160000000000000, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 225 } },
  { id: 'giantpiantatree_t8', name: 'Endless Spring',
    description: 'Giant Pianta Trees produce twice as many Durians. The season stopped ending. Nobody has complained.',
    cost: 1600000000000000.0, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 275 } },
  { id: 'giantpiantatree_t9', name: 'Heartwood Bounty',
    description: 'Giant Pianta Trees produce twice as many Durians. The fruit grows inside the trunk now.',
    cost: 1.6e+16, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 325 } },
  { id: 'giantpiantatree_t10', name: 'The Tree Remembers',
    description: 'Giant Pianta Trees produce twice as many Durians. It fruits harder for villages that treat it well.',
    cost: 1.6e+17, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 375 } },
  { id: 'giantpiantatree_t11', name: 'Skyward Growth',
    description: 'Giant Pianta Trees produce twice as many Durians. It is above the cloud layer. It is still growing.',
    cost: 1.6e+18, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 425 } },
  { id: 'giantpiantatree_t12', name: 'The World Tree',
    description: 'Giant Pianta Trees produce twice as many Durians. Isle Delfino is, arguably, a thing that grows on it.',
    cost: 1.6e+19, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerMult', target: 'giantpiantatree', value: 2 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 475 } },
  { id: 'shadowmario_t3', name: 'Thicker Paint',
    description: 'Shadow Marios produce twice as many Durians. Two coats. The durians last longer.',
    cost: 31500000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 50 } },
  { id: 'shadowmario_t4', name: 'Graffiti Tutorials',
    description: 'Shadow Marios produce twice as many Durians. He is teaching now. That seems bad.',
    cost: 315000000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 100 } },
  { id: 'shadowmario_t5', name: 'Vanishing Act',
    description: 'Shadow Marios produce twice as many Durians. Gone before the cleanup crew arrives.',
    cost: 3150000000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 150 } },
  { id: 'shadowmario_t6', name: 'Doppelgänger Shifts',
    description: 'Shadow Marios produce twice as many Durians. There are several of him. There were always several.',
    cost: 31500000000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 200 } },
  { id: 'shadowmario_t7', name: 'Paint Chemistry',
    description: 'Shadow Marios produce twice as many Durians. The formula improved. The smell did not.',
    cost: 315000000000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 250 } },
  { id: 'shadowmario_t8', name: 'Forgery Ring',
    description: 'Shadow Marios produce twice as many Durians. Indistinguishable from real durians. Legally, a grey area.',
    cost: 3150000000000000.0, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 300 } },
  { id: 'shadowmario_t9', name: 'The Brush Awakens',
    description: 'Shadow Marios produce twice as many Durians. It has started painting on its own.',
    cost: 3.15e+16, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 350 } },
  { id: 'shadowmario_t10', name: 'Impersonation Mastery',
    description: 'Shadow Marios produce twice as many Durians. Someone is running the harvest. Probably not who you think.',
    cost: 3.15e+17, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 400 } },
  { id: 'shadowmario_t11', name: 'Reality Vandalism',
    description: 'Shadow Marios produce twice as many Durians. The fruit was not there a moment ago.',
    cost: 3.15e+18, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 450 } },
  { id: 'shadowmario_t12', name: 'Paint Over Everything',
    description: 'Shadow Marios produce twice as many Durians. The island is a canvas. The canvas is durians.',
    cost: 3.15e+19, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerMult', target: 'shadowmario', value: 2 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 500 } },
  { id: 'pianta_village', name: 'Pianta Village',
    description: 'Piantas gain +1% output for every 25 you own. A whole village collecting, and every new arrival makes the rest quicker.',
    cost: 375000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerScaling', target: 'pianta', per: 25, value: 0.01 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 60 } },
  { id: 'pianta_metropolis', name: 'Pianta Metropolis',
    description: 'Piantas gain +1% output for every 10 you own. The village grew. It has districts now, and a durian exchange.',
    cost: 6000000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerScaling', target: 'pianta', per: 10, value: 0.01 }],
    unlock: { type: 'workerCount', id: 'pianta', count: 200 } },
  { id: 'noki_colony', name: 'Noki Colony',
    description: 'Nokis gain +1% output for every 25 you own. Shells stacked into towers, each one full of fruit.',
    cost: 900000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerScaling', target: 'noki', per: 25, value: 0.01 }],
    unlock: { type: 'workerCount', id: 'noki', count: 60 } },
  { id: 'noki_abyss_city', name: 'Abyssal Reef City',
    description: 'Nokis gain +1% output for every 10 you own. Lit by something down there that nobody has named yet.',
    cost: 13500000000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerScaling', target: 'noki', per: 10, value: 0.01 }],
    unlock: { type: 'workerCount', id: 'noki', count: 200 } },
  { id: 'yoshi_ranch', name: 'Yoshi Ranch',
    description: 'Yoshis gain +2.5% output for every 10 you own. Fenced, mostly. The fence is decorative.',
    cost: 6000000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerScaling', target: 'yoshi', per: 10, value: 0.025 }],
    unlock: { type: 'workerCount', id: 'yoshi', count: 60 } },
  { id: 'toad_township', name: 'Toad Township',
    description: 'Toads gain +1% output for every 10 you own. Incorporated last Tuesday. Population: too many.',
    cost: 45000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerScaling', target: 'toad', per: 10, value: 0.01 }],
    unlock: { type: 'workerCount', id: 'toad', count: 60 } },
  { id: 'piantissimo_league', name: 'The Piantissimo League',
    description: 'Il Piantissimo gain +1.5% output for every 10 you own. Every member wears the mask. Every member insists it is not a costume.',
    cost: 300000000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerScaling', target: 'piantissimo', per: 10, value: 0.015 }],
    unlock: { type: 'workerCount', id: 'piantissimo', count: 60 } },
  { id: 'shadow_gallery', name: 'The Shadow Gallery',
    description: 'Shadow Marios gain +2% output for every 10 you own. Wing after wing of painted fruit, and none of it should exist.',
    cost: 6000000000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerScaling', target: 'shadowmario', per: 10, value: 0.02 }],
    unlock: { type: 'workerCount', id: 'shadowmario', count: 60 } },
  { id: 'fruitlady_market', name: 'The Whole Market',
    description: 'Fruit Ladies gain +6% output for every 10 you own. Stall after stall, all the way round the fountain.',
    cost: 180000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerScaling', target: 'fruitlady', per: 10, value: 0.06 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 60 } },
  { id: 'fruitlady_dynasty', name: 'Fruit Dynasty',
    description: 'Fruit Ladies gain +10% output for every 10 you own. Daughters, nieces, cousins. All of them know which durians are ready.',
    cost: 3000000000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerScaling', target: 'fruitlady', per: 10, value: 0.1 }],
    unlock: { type: 'workerCount', id: 'fruitlady', count: 200 } },
  { id: 'mushroom_network', name: 'The Dealer Network',
    description: 'Mushroom Dealers gain +8% output for every 10 you own. Every beach has one now. They wave at each other.',
    cost: 120000000000, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerScaling', target: 'mushroompianta', per: 10, value: 0.08 }],
    unlock: { type: 'workerCount', id: 'mushroompianta', count: 60 } },
  { id: 'tanooki_grove', name: 'The False Grove',
    description: 'Tanookis gain +2% output for every 10 you own. It photographs as woodland. It is entirely Tanooki.',
    cost: 900000000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerScaling', target: 'tanooki', per: 10, value: 0.02 }],
    unlock: { type: 'workerCount', id: 'tanooki', count: 60 } },
  { id: 'chuckster_yard', name: 'The Chucking Yard',
    description: 'Chucksters gain +2.5% output for every 10 you own. A cleared field, a horizon, and a great deal of shouting.',
    cost: 135000000000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerScaling', target: 'chuckster', per: 10, value: 0.025 }],
    unlock: { type: 'workerCount', id: 'chuckster', count: 60 } },
  { id: 'ricco_refinery', name: 'The Harbour Refinery',
    description: 'Ricco Converters gain +3% output for every 10 you own. A whole dock given over to it. The smell carries for miles.',
    cost: 60000000000000, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerScaling', target: 'riccoconverter', per: 10, value: 0.03 }],
    unlock: { type: 'workerCount', id: 'riccoconverter', count: 60 } },
  { id: 'tree_orchard', name: 'The Village Orchard',
    description: 'Giant Pianta Trees gain +3% output for every 10 you own. Saplings from the great tree, and every one of them enormous.',
    cost: 3000000000000000.0, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerScaling', target: 'giantpiantatree', per: 10, value: 0.03 }],
    unlock: { type: 'workerCount', id: 'giantpiantatree', count: 60 } },
  { id: 'syn_noki_teach', name: 'Neighbourly Advice',
    description: 'Piantas gain +0.2% output for each Noki you own. The Nokis explain tides. The Piantas nod and work faster.',
    cost: 2250000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerSynergy', target: 'pianta', source: 'noki', value: 0.002 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_pianta_muscle', name: 'Borrowed Muscle',
    description: 'Nokis gain +0.2% output for each Pianta you own. Heavy lifting outsourced to the neighbours.',
    cost: 2700000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerSynergy', target: 'noki', source: 'pianta', value: 0.002 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_yoshi_ride', name: 'Ride Sharing',
    description: 'Piantas gain +0.2% output for each Yoshi you own. Every Pianta with a Yoshi covers four times the ground.',
    cost: 12000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerSynergy', target: 'pianta', source: 'yoshi', value: 0.002 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_pianta_feed', name: 'Feeding Rotation',
    description: 'Yoshis gain +0.4% output for each worker you own. Someone has to keep them fed. It may as well be everyone.',
    cost: 13500000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerSynergy', target: 'yoshi', source: 'all', value: 0.004 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_noki_freight', name: 'Harbour Contracts',
    description: 'Toads gain +1% output for each Noki you own. The Toads book the freight. The Nokis do the swimming.',
    cost: 90000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerSynergy', target: 'toad', source: 'noki', value: 0.01 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_toad_pace', name: 'Pace Setters',
    description: 'Il Piantissimo gain +0.3% output for each worker you own. He needs someone to beat. The Toads volunteer, unwisely.',
    cost: 750000000000, icon: 'assets/placeholder-piantissimo.png',
    effects: [{ type: 'workerSynergy', target: 'piantissimo', source: 'all', value: 0.003 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_all_shadow', name: 'Painted Over',
    description: 'Shadow Marios gain +0.3% output for each worker you own. The more of the island there is, the more of it he can copy.',
    cost: 12000000000000, icon: 'assets/placeholder-shadowmario.png',
    effects: [{ type: 'workerSynergy', target: 'shadowmario', source: 'all', value: 0.003 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_shadow_pianta', name: 'Forged Work Orders',
    description: 'Piantas gain +0.5% output for each Shadow Mario you own. The orders are fake. The overtime is real.',
    cost: 15000000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerSynergy', target: 'pianta', source: 'shadowmario', value: 0.005 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_piantissimo_noki', name: 'Record Pace',
    description: 'Nokis gain +0.5% output for each Il Piantissimo you own. Nobody wants to be the slow one in the water.',
    cost: 18000000000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerSynergy', target: 'noki', source: 'piantissimo', value: 0.005 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_toad_yoshi', name: 'Saddle Supply',
    description: 'Yoshis gain +0.3% output for each worker you own. Toads make the saddles. Yoshis pretend to like them.',
    cost: 600000000000, icon: 'assets/placeholder-yoshi.png',
    effects: [{ type: 'workerSynergy', target: 'yoshi', source: 'all', value: 0.003 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_yoshi_toad', name: 'Fruit Tithe',
    description: 'Toads gain +0.3% output for each worker you own. A cut of every mouthful goes to the Toads. Somehow.',
    cost: 450000000000, icon: 'assets/placeholder-toad.png',
    effects: [{ type: 'workerSynergy', target: 'toad', source: 'all', value: 0.003 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_fruitlady_pianta', name: 'Stall Supply Run',
    description: 'Fruit Ladies gain +2% output for each Pianta you own. The Piantas bring it in, she sells it on. An old arrangement.',
    cost: 3000000000, icon: 'assets/placeholder-fruitlady.png',
    effects: [{ type: 'workerSynergy', target: 'fruitlady', source: 'pianta', value: 0.02 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_pianta_fruitlady', name: 'Family Discount',
    description: 'Piantas gain +0.6% output for each Fruit Ladie you own. Everyone in the Plaza is related to her somehow.',
    cost: 4500000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerSynergy', target: 'pianta', source: 'fruitlady', value: 0.006 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_mushroom_toad', name: 'Awkward Overlap',
    description: 'Mushroom Dealers gain +2% output for each Toad you own. The Toads have opinions about the mushroom trade. He ignores them.',
    cost: 135000000000, icon: 'assets/placeholder-mushroompianta.png',
    effects: [{ type: 'workerSynergy', target: 'mushroompianta', source: 'toad', value: 0.02 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_tanooki_yoshi', name: 'Mistaken Identity',
    description: 'Tanookis gain +0.8% output for each Yoshi you own. The Yoshis keep trying to eat the trees. Some of the trees complain.',
    cost: 1050000000000, icon: 'assets/placeholder-tanooki.png',
    effects: [{ type: 'workerSynergy', target: 'tanooki', source: 'yoshi', value: 0.008 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_chuckster_all', name: 'Everything Gets Thrown',
    description: 'Chucksters gain +0.3% output for each worker you own. If it can be lifted, it will be thrown. Nothing on the island is safe.',
    cost: 75000000000000, icon: 'assets/placeholder-chuckster.png',
    effects: [{ type: 'workerSynergy', target: 'chuckster', source: 'all', value: 0.003 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_all_chuckster', name: 'Air Freight',
    description: 'All workers gain +0.2% output for each Chuckster you own. Nobody carries anything by hand any more.',
    cost: 120000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'workerSynergy', target: 'all', source: 'chuckster', value: 0.002 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_ricco_all', name: 'Everything Is Fruit',
    description: 'Ricco Converters gain +0.2% output for each worker you own. If it grows on the island, it ends up in the hopper.',
    cost: 90000000000000, icon: 'assets/placeholder-riccoconverter.png',
    effects: [{ type: 'workerSynergy', target: 'riccoconverter', source: 'all', value: 0.002 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_tree_pianta', name: 'Village Devotion',
    description: 'Giant Pianta Trees gain +0.4% output for each Pianta you own. Every Pianta in the village tends it. The tree notices.',
    cost: 6000000000000000.0, icon: 'assets/placeholder-giantpiantatree.png',
    effects: [{ type: 'workerSynergy', target: 'giantpiantatree', source: 'pianta', value: 0.004 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'syn_census', name: 'Island Census',
    description: 'All workers gain +0% output for each worker you own. Everyone counted, everyone accounted for, everyone working.',
    cost: 30000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'workerSynergy', target: 'all', source: 'all', value: 0.0002 }],
    unlock: { type: 'totalWorkers', count: 120 } },
  { id: 'gloves3', name: 'Spike-Proof Gauntlets',
    description: '+50 Durians per click. The gloves have gloves.',
    cost: 750000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickAdd', value: 50 }],
    unlock: { type: 'clicks', count: 300 } },
  { id: 'gloves4', name: 'Harvest Claws',
    description: '+500 Durians per click. Legally not a weapon.',
    cost: 30000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickAdd', value: 500 }],
    unlock: { type: 'clicks', count: 500 } },
  { id: 'gloves5', name: 'Hydraulic Grip',
    description: '+5,000 Durians per click. Rated for structural demolition.',
    cost: 1200000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickAdd', value: 5000 }],
    unlock: { type: 'clicks', count: 700 } },
  { id: 'gloves6', name: 'The Grasping Hand',
    description: '+100,000 Durians per click. It closes on its own sometimes.',
    cost: 60000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickAdd', value: 100000 }],
    unlock: { type: 'clicks', count: 900 } },
  { id: 'fludd_rocket', name: 'Rocket Nozzle',
    description: 'Durians per click ×1.5. Straight up into the canopy.',
    cost: 750000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickMult', value: 1.5 }],
    unlock: { type: 'clicks', count: 1100 } },
  { id: 'fludd_yoshi', name: 'Yoshi-Assisted Clicking',
    description: 'Durians per click ×1.5. He does the reaching.',
    cost: 90000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickMult', value: 1.5 }],
    unlock: { type: 'clicks', count: 1300 } },
  { id: 'fludd_overclock', name: 'Overclocked FLUDD',
    description: 'Durians per click ×1.5. The warranty is extremely void.',
    cost: 13500000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickMult', value: 1.5 }],
    unlock: { type: 'clicks', count: 1500 } },
  { id: 'click_dps3', name: 'Pressure Washer',
    description: 'Each click earns a further 0.2% of your Durians per second.',
    cost: 3000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromDps', value: 0.002 }],
    unlock: { type: 'clicks', count: 1700 } },
  { id: 'click_dps4', name: 'Industrial Manifold',
    description: 'Each click earns a further 0.2% of your Durians per second.',
    cost: 750000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromDps', value: 0.002 }],
    unlock: { type: 'clicks', count: 1900 } },
  { id: 'click_dps5', name: 'The Whole Island At Once',
    description: 'Each click earns a further 0.2% of your Durians per second.',
    cost: 1200000000000000.0, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromDps', value: 0.002 }],
    unlock: { type: 'clicks', count: 2100 } },
  { id: 'click_crew1', name: 'Supervised Clicking',
    description: '+10 Durians per click for every worker you employ.',
    cost: 1500000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromWorkers', value: 10 }],
    unlock: { type: 'clicks', count: 2300 } },
  { id: 'click_crew2', name: 'Everybody Helps',
    description: '+250 Durians per click for every worker you employ.',
    cost: 450000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromWorkers', value: 250 }],
    unlock: { type: 'clicks', count: 2500 } },
  { id: 'click_crew3', name: 'The Island Clicks With You',
    description: '+10,000 Durians per click for every worker you employ.',
    cost: 900000000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickFromWorkers', value: 10000 }],
    unlock: { type: 'clicks', count: 2700 } },
  { id: 'click_callus', name: 'Legendary Calluses',
    description: 'Durians per click ×1.5. Your hands are a geological feature.',
    cost: 300000000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickMult', value: 1.5 }],
    unlock: { type: 'clicks', count: 2900 } },
  { id: 'click_myth', name: 'The Shine Touch',
    description: 'Doubles Durians per click. Everything you touch ripens.',
    cost: 1.2e+16, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'clickMult', value: 2 }],
    unlock: { type: 'clicks', count: 3100 } },
  { id: 'world_plaza', name: 'Delfino Plaza Cleanup',
    description: 'All workers produce +15% Durians. Scrub the goop off the fountain and the whole island works better.',
    cost: 90000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.15 }],
    unlock: { type: 'totalEarned', amount: 54000000 } },
  { id: 'world_bianco', name: 'Bianco Hills Windmill',
    description: 'All workers produce +15% Durians. It grinds durians now. It was never supposed to grind durians.',
    cost: 450000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.15 }],
    unlock: { type: 'totalEarned', amount: 270000000 } },
  { id: 'world_ricco', name: 'Ricco Harbour Cranes',
    description: 'All workers produce +20% Durians. Industrial fruit handling, finally.',
    cost: 2250000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.2 }],
    unlock: { type: 'totalEarned', amount: 1350000000 } },
  { id: 'world_gelato', name: 'Le Sandbird is Born',
    description: 'All workers produce +20% Durians. It woke up. It seems fine with the arrangement.',
    cost: 12000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.2 }],
    unlock: { type: 'totalEarned', amount: 7200000000 } },
  { id: 'world_pinna', name: 'Pinna Park Rides',
    description: 'All workers produce +25% Durians. The rollercoaster doubles as a conveyor belt.',
    cost: 60000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.25 }],
    unlock: { type: 'totalEarned', amount: 36000000000 } },
  { id: 'world_sirena', name: 'Sirena Beach Renovation',
    description: 'All workers produce +25% Durians. The hotel reopens. The staffing situation remains unclear.',
    cost: 300000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.25 }],
    unlock: { type: 'totalEarned', amount: 180000000000 } },
  { id: 'world_noki_bay', name: 'Noki Bay Purification',
    description: 'All workers produce +30% Durians. Clean water at last. The fruit tastes worse and sells better.',
    cost: 1500000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.3 }],
    unlock: { type: 'totalEarned', amount: 900000000000 } },
  { id: 'world_pianta_village', name: 'Pianta Village Canopy',
    description: 'All workers produce +30% Durians. Above the clouds, where the biggest durians grow.',
    cost: 7500000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.3 }],
    unlock: { type: 'totalEarned', amount: 4500000000000 } },
  { id: 'world_corona', name: 'Corona Mountain',
    description: 'All workers produce +100% Durians. The volcano is just spewing durians now. Nobody can explain it. Nobody is complaining.',
    cost: 45000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 2 }],
    unlock: { type: 'totalEarned', amount: 27000000000000 } },
  { id: 'world_airstrip', name: 'Delfino Airstrip Exports',
    description: 'All workers produce +35% Durians. Wheels up, hold full, smell detectable at altitude.',
    cost: 300000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.35 }],
    unlock: { type: 'totalEarned', amount: 180000000000000 } },
  { id: 'world_plaza2', name: 'Plaza Grand Festival',
    description: 'All workers produce +20% Durians. Annual. Mandatory. Extremely productive.',
    cost: 1200000000000000.0, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.2 }],
    unlock: { type: 'totalEarned', amount: 720000000000000 } },
  { id: 'world_bianco2', name: 'Bianco Terraces',
    description: 'All workers produce +25% Durians. Every hillside, every slope, every square inch under fruit.',
    cost: 4500000000000000.0, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.25 }],
    unlock: { type: 'totalEarned', amount: 2700000000000000.0 } },
  { id: 'world_ricco2', name: 'Harbour Superport',
    description: 'All workers produce +25% Durians. Ships arrive empty and leave sitting worryingly low.',
    cost: 1.5e+16, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.25 }],
    unlock: { type: 'totalEarned', amount: 9000000000000000.0 } },
  { id: 'world_gelato2', name: 'Gelato Reef Farms',
    description: 'All workers produce +30% Durians. Underwater orchards. The coral has opinions.',
    cost: 7.5e+16, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.3 }],
    unlock: { type: 'totalEarned', amount: 4.5e+16 } },
  { id: 'world_pinna2', name: 'Pinna Park Expansion',
    description: 'All workers produce +30% Durians. A second park, built entirely to process the first park.',
    cost: 3e+17, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.3 }],
    unlock: { type: 'totalEarned', amount: 1.8e+17 } },
  { id: 'world_sirena2', name: 'Sirena Grand Resort',
    description: 'All workers produce +35% Durians. Five stars. The reviews mention the smell. The reviews are positive.',
    cost: 1.35e+18, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.35 }],
    unlock: { type: 'totalEarned', amount: 8.1e+17 } },
  { id: 'world_noki2', name: 'Noki Deep Cultivation',
    description: 'All workers produce +35% Durians. Trenches planted to a depth nobody has surveyed.',
    cost: 6e+18, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.35 }],
    unlock: { type: 'totalEarned', amount: 3.6e+18 } },
  { id: 'world_village2', name: 'The Great Canopy',
    description: 'All workers produce +40% Durians. The treetops have merged into one continuous orchard.',
    cost: 3e+19, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.4 }],
    unlock: { type: 'totalEarned', amount: 1.8e+19 } },
  { id: 'world_corona2', name: 'Corona Eruption',
    description: 'All workers produce +150% Durians. It erupted. It rained durians for nine days. The island got richer.',
    cost: 6e+18, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 2.5 }],
    unlock: { type: 'totalEarned', amount: 3.6e+18 } },
  { id: 'world_delfino', name: 'All of Isle Delfino',
    description: 'All workers produce +50% Durians. Every district, every beach, every last inhabitant. Working.',
    cost: 1.5e+19, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.5 }],
    unlock: { type: 'totalEarned', amount: 9e+18 } },
  { id: 'shine_hoard1', name: 'Shine Sprite Hoard',
    description: 'Each Shine you have earned adds +1% to all production.',
    cost: 7500000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'achievementBonus', value: 0.01 }],
    unlock: { type: 'achievementCount', count: 18 } },
  { id: 'shine_hoard2', name: 'Shine Gallery',
    description: 'Each Shine earned adds a further +2% to all production.',
    cost: 1200000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'achievementBonus', value: 0.02 }],
    unlock: { type: 'achievementCount', count: 24 } },
  { id: 'shine_hoard3', name: 'Shine Vault',
    description: 'Each Shine earned adds a further +3% to all production.',
    cost: 75000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'achievementBonus', value: 0.03 }],
    unlock: { type: 'achievementCount', count: 30 } },
  { id: 'shine_hoard4', name: 'Shine Constellation',
    description: 'Each Shine earned adds a further +5% to all production.',
    cost: 6000000000000000.0, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'achievementBonus', value: 0.05 }],
    unlock: { type: 'achievementCount', count: 36 } },
  { id: 'shine_hoard5', name: 'The Shine Throne',
    description: 'Each Shine earned adds a further +8% to all production.',
    cost: 3e+17, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'achievementBonus', value: 0.08 }],
    unlock: { type: 'achievementCount', count: 42 } },
  { id: 'shine_hoard6', name: 'Sunlight Itself',
    description: 'Each Shine earned adds a further +12% to all production.',
    cost: 3e+18, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'achievementBonus', value: 0.12 }],
    unlock: { type: 'achievementCount', count: 48 } },
  { id: 'luck_charm', name: 'Rusty Lucky Charm',
    description: 'Island events happen 25% more often.',
    cost: 3000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventChance', value: 1.25 }],
    unlock: { type: 'eventsSeen', count: 3 } },
  { id: 'luck_charm2', name: 'Polished Lucky Charm',
    description: 'Island events happen a further 25% more often.',
    cost: 600000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventChance', value: 1.25 }],
    unlock: { type: 'eventsSeen', count: 7 } },
  { id: 'luck_charm3', name: 'Blessed Lucky Charm',
    description: 'Island events happen 50% more often again.',
    cost: 90000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventChance', value: 1.5 }],
    unlock: { type: 'eventsSeen', count: 11 } },
  { id: 'boo_bargain', name: 'King Boo\'s Bargain',
    description: 'Good island events pay out twice as much.',
    cost: 15000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventGain', value: 2 }],
    unlock: { type: 'eventsSeen', count: 15 } },
  { id: 'boo_bargain2', name: 'A Deal in Writing',
    description: 'Good island events pay out twice as much again.',
    cost: 12000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventGain', value: 2 }],
    unlock: { type: 'eventsSeen', count: 19 } },
  { id: 'hotel_haggling', name: 'Hotel Haggling',
    description: 'Bad island events cost you half as much, and bad buffs wear off twice as fast.',
    cost: 7500000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventLoss', value: 0.5 }],
    unlock: { type: 'eventsSeen', count: 23 } },
  { id: 'hotel_lawyer', name: 'A Very Good Lawyer',
    description: 'Bad island events cost 60% less and bad buffs fade faster. She is worth every Durian.',
    cost: 3000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventLoss', value: 0.4 }],
    unlock: { type: 'eventsSeen', count: 27 } },
  { id: 'hotel_insurance', name: 'Sirena Beach Insurance',
    description: 'Bad island events cost 70% less and bad buffs barely last. The premiums are absurd.',
    cost: 1350000000000000.0, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'eventLoss', value: 0.3 }],
    unlock: { type: 'eventsSeen', count: 31 } },
  { id: 'buff_bottle', name: 'Bottled Sunshine',
    description: 'Good island buffs last 50% longer.',
    cost: 45000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'buffDuration', value: 1.5 }],
    unlock: { type: 'eventsSeen', count: 35 } },
  { id: 'buff_bottle2', name: 'Sunlight Preserve',
    description: 'Good island buffs last twice as long again.',
    cost: 75000000000000, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'buffDuration', value: 2 }],
    unlock: { type: 'eventsSeen', count: 39 } },
  { id: 'offline1', name: 'Night Shift',
    description: 'Workers produce 25% more while you are away.',
    cost: 600000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'offlineEfficiency', value: 0.25 }],
    unlock: { type: 'totalEarned', amount: 300000000 } },
  { id: 'offline2', name: 'Double Shift',
    description: 'A further 25% more while you are away.',
    cost: 90000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'offlineEfficiency', value: 0.25 }],
    unlock: { type: 'totalEarned', amount: 45000000000 } },
  { id: 'offline3', name: 'They Never Stop',
    description: 'A further 50% more while you are away.',
    cost: 30000000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'offlineEfficiency', value: 0.5 }],
    unlock: { type: 'totalEarned', amount: 15000000000000 } },
  { id: 'offline_time1', name: 'Longer Leave',
    description: 'Offline earnings now accumulate for up to 36 hours.',
    cost: 4500000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'offlineHours', value: 12 }],
    unlock: { type: 'totalEarned', amount: 2250000000 } },
  { id: 'offline_time2', name: 'Extended Leave',
    description: 'Offline earnings now accumulate for up to 72 hours.',
    cost: 1500000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'offlineHours', value: 36 }],
    unlock: { type: 'totalEarned', amount: 750000000000 } },
  { id: 'offline_time3', name: 'Indefinite Sabbatical',
    description: 'Offline earnings now accumulate for up to a week.',
    cost: 600000000000000, icon: 'assets/placeholder-upgrade.png',
    effects: [{ type: 'offlineHours', value: 96 }],
    unlock: { type: 'totalEarned', amount: 300000000000000 } },
  { id: 'grand1', name: 'Durian Standard',
    description: 'All workers produce 1.5x as many Durians. The island currency is now fruit. It was always going to be fruit.',
    cost: 3e+19, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.5 }],
    unlock: { type: 'totalEarned', amount: 1.5e+19 } },
  { id: 'grand2', name: 'Continental Shipping',
    description: 'All workers produce 1.5x as many Durians. Other islands have heard. Other islands are afraid.',
    cost: 2.25e+20, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.5 }],
    unlock: { type: 'totalEarned', amount: 1.125e+20 } },
  { id: 'grand3', name: 'The Smell Reaches Space',
    description: 'All workers produce 1.75x as many Durians. Satellites have reported it. Nobody is investigating.',
    cost: 1.5e+21, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 1.75 }],
    unlock: { type: 'totalEarned', amount: 7.5e+20 } },
  { id: 'grand4', name: 'Orbital Orchard',
    description: 'All workers produce 2x as many Durians. Fruit in low Delfino orbit. It seemed like the next step.',
    cost: 1.2e+22, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 2 }],
    unlock: { type: 'totalEarned', amount: 6e+21 } },
  { id: 'grand5', name: 'Durian Singularity',
    description: 'All workers produce 2.5x as many Durians. Production now exceeds the island’s ability to describe it.',
    cost: 9e+22, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 2.5 }],
    unlock: { type: 'totalEarned', amount: 4.5e+22 } },
  { id: 'grand6', name: 'The Fruit Age',
    description: 'All workers produce 3x as many Durians. Historians will call it that. Historians will also be harvesting.',
    cost: 7.5e+23, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'globalMult', value: 3 }],
    unlock: { type: 'totalEarned', amount: 3.75e+23 } },
  { id: 'rescue_pianta1', name: 'Pianta Pride',
    description: 'Piantas gain +1% output for each Shadow Mario you own. They refuse to be outdone by a fake.',
    cost: 75000000000000, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerSynergy', target: 'pianta', source: 'shadowmario', value: 0.01 }],
    unlock: { type: 'totalEarned', amount: 37500000000000 } },
  { id: 'rescue_pianta2', name: 'The First Harvesters',
    description: 'Piantas gain +0.2% output for each worker you own. They were here first and everyone knows it.',
    cost: 3000000000000000.0, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerSynergy', target: 'pianta', source: 'all', value: 0.002 }],
    unlock: { type: 'totalEarned', amount: 1500000000000000.0 } },
  { id: 'rescue_noki1', name: 'Noki Deep Contracts',
    description: 'Nokis gain +1% output for each Il Piantissimo you own. Somebody has to fish him out.',
    cost: 120000000000000, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerSynergy', target: 'noki', source: 'piantissimo', value: 0.01 }],
    unlock: { type: 'totalEarned', amount: 60000000000000 } },
  { id: 'rescue_noki2', name: 'The Old Currents',
    description: 'Nokis gain +0.2% output for each worker you own. Every route on Delfino was theirs first.',
    cost: 4500000000000000.0, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerSynergy', target: 'noki', source: 'all', value: 0.002 }],
    unlock: { type: 'totalEarned', amount: 2250000000000000.0 } },
  { id: 'rescue_starters', name: 'Founding Crew',
    description: 'Piantas gain +0.5% output for each Noki you own. The original two, still carrying the island.',
    cost: 6e+16, icon: 'assets/placeholder-pianta.png',
    effects: [{ type: 'workerSynergy', target: 'pianta', source: 'noki', value: 0.005 }],
    unlock: { type: 'totalEarned', amount: 3e+16 } },
  { id: 'rescue_starters2', name: 'Founding Crew II',
    description: 'Nokis gain +0.5% output for each Pianta you own. The arrangement is mutual and slightly competitive.',
    cost: 6e+16, icon: 'assets/placeholder-noki.png',
    effects: [{ type: 'workerSynergy', target: 'noki', source: 'pianta', value: 0.005 }],
    unlock: { type: 'totalEarned', amount: 3e+16 } },
  { id: 'rescue_legacy', name: 'Nobody Forgets',
    description: 'All workers gain +0.1% output for each Pianta you own. The island runs on their example.',
    cost: 9e+16, icon: 'assets/placeholder-shine.png',
    effects: [{ type: 'workerSynergy', target: 'all', source: 'pianta', value: 0.001 }],
    unlock: { type: 'totalEarned', amount: 4.5e+16 } }
  ]);
})(window.DC = window.DC || {});
